version: '3.8'
services:
  postgres-primary:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=admin
      - POSTGRESQL_DATABASE=my_app_db
    ports:
      - "5432:5432"

  postgres-replica:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=postgres-primary
      - POSTGRESQL_PASSWORD=admin
    ports:
      - "5433:5432"
    depends_on:
      - postgres-primary

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"